SET foreign_key_checks = 0;

DROP TABLE IF EXISTS FormData;
DROP TABLE IF EXISTS Form;
DROP TABLE IF EXISTS FormField;
DROP TABLE IF EXISTS FormTemplate;
DROP TABLE IF EXISTS FieldValidationRule;
DROP TABLE IF EXISTS FieldType;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Dictionary;

SET foreign_key_checks = 1;

CREATE TABLE Dictionary
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(256) NOT NULL UNIQUE,
    Value VARCHAR(256) NOT NULL,
    Description VARCHAR(4000) NULL,
    ParentId INT(6) UNSIGNED,
    FOREIGN KEY (ParentId) REFERENCES Dictionary(Id)
);

CREATE TABLE Tag
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(256) NOT NULL UNIQUE,
    Title VARCHAR(256) NOT NULL,
    Description VARCHAR(4000) NULL
);

CREATE TABLE FieldType
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(256) NOT NULL UNIQUE,
    Title VARCHAR(256) NOT NULL,
    DataType INT(2) UNSIGNED NOT NULL
);

CREATE TABLE FieldValidationRule
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(256) NOT NULL UNIQUE,
    Description VARCHAR(256) NOT NULL,
    Pattern VARCHAR(256) NOT NULL,
    Message VARCHAR(4000) NOT NULL,
    FieldTypeId INT(6) UNSIGNED NULL,
    FOREIGN KEY (FieldTypeId) REFERENCES FieldType(Id)
);

CREATE TABLE FormTemplate
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(256) NOT NULL UNIQUE,
    Title VARCHAR(256) NOT NULL,
	TagId INT(6) UNSIGNED,
	FOREIGN KEY (TagId) REFERENCES Dictionary(Id)
);

CREATE TABLE FormField
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    Name VARCHAR(256) NOT NULL UNIQUE,
    Title VARCHAR(256) NOT NULL,
    Code VARCHAR(256) NULL,
    TemplateId INT(6) UNSIGNED NOT NULL,
    FieldTypeId INT(6) UNSIGNED NOT NULL,
    CustomValidationId INT(6) UNSIGNED NULL,
    TagId INT(6) UNSIGNED,
    FOREIGN KEY (TemplateId) REFERENCES FormTemplate(Id),
    FOREIGN KEY (FieldTypeId) REFERENCES FieldType(Id),
    FOREIGN KEY (CustomValidationId) REFERENCES FieldValidationRule(Id),
    FOREIGN KEY (TagId) REFERENCES Dictionary(Id)
);

CREATE TABLE Form
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    TemplateId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (TemplateId) REFERENCES FormTemplate(Id)
);

CREATE TABLE FormData
(
	Id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	AddDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	AddLogin VARCHAR(256) NOT NULL,
	ModifDate TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	ModifLogin VARCHAR(256) NULL,
	IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    IntValue INT(12) NULL,
    StringValue VARCHAR(4000) NULL,
    DecimalValue DECIMAL(15,3) NULL,
    DateTimeValue TIMESTAMP NULL,
    FieldId INT(6) UNSIGNED NOT NULL,
    FormId INT(6) UNSIGNED NOT NULL,
    FOREIGN KEY (FieldId) REFERENCES FormField(Id),
    FOREIGN KEY (FormId) REFERENCES Form(Id)
);